version: '2'

services:
  totum:
    image: totum_image
    restart: always
    ports:
      - 80:80
    volumes: 
      - totum_volume:/var/lib/postgresql

volumes:
  totum_volume:
    driver: local
